name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lemici-flask:1.0 .

      # Step 3: Run tests 
      - name: Run tests
        run: echo "Tests passed"

      # Step 4: Push Docker image to DockerHub
      - name: Push image to DockerHub
        run: |
          echo "Logging into DockerHub..."
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lemici-flask:1.0
